export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  try {
    const { imageData, mimeType } = req.body;
    if (!imageData || !mimeType) return res.status(400).json({ error: 'Missing imageData or mimeType' });

    // --- Hive v3 ---
    const r = await fetch('https://api.thehive.ai/api/v3/hive/ai-generated-and-deepfake-content-detection', {
      method: 'POST',
      headers: { 'Authorization': 'Bearer ' + process.env.HIVE_API_KEY, 'Content-Type': 'application/json' },
      body: JSON.stringify({ input: [{ media_base64: 'data:' + mimeType + ';base64,' + imageData }] })
    });
    const d = await r.json();
    if (d.error || d.detail) return res.status(500).json({ error: d.error || String(d.detail) });

    const classes = d.output?.[0]?.classes || [];
    const aiClass = classes.find(c => c.class === 'ai_generated');
    const deepfakeClass = classes.find(c => c.class === 'deepfake');

    if (!aiClass) return res.status(500).json({ error: 'No classification data from Hive', debug: JSON.stringify(d).slice(0, 300) });

    const isAI = aiClass.value >= 0.5;
    const aiScore = isAI ? Math.min(95, Math.max(55, Math.round(aiClass.value * 100))) : Math.min(45, Math.max(5, Math.round(aiClass.value * 100)));
    const realScore = 100 - aiScore;
    const verdict = isAI ? 'AI_GENERATED' : 'AUTHENTIC';

    // Deepfake
    const isDeepfake = (deepfakeClass?.value || 0) >= 0.5;
    const deepfakeScore = Math.round((deepfakeClass?.value || 0) * 100);

    // Generator detection — known generators from Hive
    const generatorNames = ['midjourney','dalle','stablediffusion','stablediffusionxl','flux','ideogram','adobefirefly','leonardo','4o','grok','imagen','sana','emu3','omnigen','gptimage1_5','hidream','pixart','kandinsky'];
    const detectedGenerators = generatorNames
      .map(name => ({ name, value: classes.find(c => c.class === name)?.value || 0 }))
      .filter(g => g.value > 0.1)
      .sort((a, b) => b.value - a.value)
      .slice(0, 3);

    // Format generator name nicely
    const formatGen = name => ({
      midjourney: 'Midjourney', dalle: 'DALL-E', stablediffusion: 'Stable Diffusion',
      stablediffusionxl: 'Stable Diffusion XL', flux: 'Flux', ideogram: 'Ideogram',
      adobefirefly: 'Adobe Firefly', leonardo: 'Leonardo AI', '4o': 'GPT-4o',
      grok: 'Grok', imagen: 'Imagen', sana: 'Sana', emu3: 'EMU3',
      omnigen: 'OmniGen', gptimage1_5: 'GPT Image 1.5', hidream: 'HiDream',
      pixart: 'PixArt', kandinsky: 'Kandinsky'
    }[name] || name);

    // --- Gemini explanation ---
    const geminiPrompt = `A specialized AI detection system classified this image as ${isAI ? 'AI GENERATED' : 'AUTHENTIC'}.${isDeepfake ? ' A deepfake face was also detected.' : ''}

Examine the image and write exactly 4 bullet points explaining specific visual evidence.
${isAI ? 'Focus on: skin texture, fingers/hands, hair, facial symmetry, background, lighting, eyes.' : 'Focus on: film grain, skin imperfections, depth of field, shadow consistency, background detail.'}

Format as exactly 4 lines starting with a dash:
- [area]: [observation]
- [area]: [observation]
- [area]: [observation]
- [area]: [observation]

Then one line starting with SUMMARY:`;

    const geminiRes = await fetch(
      `https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash:generateContent?key=${process.env.GEMINI_API_KEY}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [{ parts: [{ text: geminiPrompt }, { inline_data: { mime_type: mimeType, data: imageData } }] }],
          generationConfig: { maxOutputTokens: 2048, temperature: 0.0 }
        })
      }
    );

    const geminiData = await geminiRes.json();
    const raw = geminiData?.candidates?.[0]?.content?.parts?.[0]?.text || '';

    let indicators = [{ type: 'neutral', text: 'Hive → ' + (isAI ? 'AI Generated' : 'Authentic') + ' (' + Math.round(aiClass.value * 100) + '% confidence)' }];
    let summary = isAI ? 'This image was likely generated by an AI model.' : 'This image appears to be authentic.';

    if (raw) {
      const lines = raw.split('\n').map(l => l.trim()).filter(Boolean);
      const bullets = lines.filter(l => l.startsWith('-')).map(l => l.replace(/^-\s*/, '').replace(/\*\*/g, '').trim()).filter(l => l.length > 10).slice(0, 4);
      const summaryLine = lines.find(l => l.startsWith('SUMMARY:'));
      if (bullets.length > 0) {
        indicators = [
          { type: 'neutral', text: 'Hive → ' + (isAI ? 'AI Generated' : 'Authentic') + ' (' + Math.round(aiClass.value * 100) + '% confidence)' },
          ...bullets.map(text => ({ type: isAI ? 'ai' : 'real', text }))
        ];
      }
      if (summaryLine) summary = summaryLine.replace('SUMMARY:', '').trim();
    }

    return res.status(200).json({
      verdict,
      confidence: Math.round(aiClass.value * 100),
      ai_probability: aiScore,
      authentic_probability: realScore,
      deepfake: { detected: isDeepfake, score: deepfakeScore },
      generators: detectedGenerators.map(g => ({ name: formatGen(g.name), score: Math.round(g.value * 100) })),
      indicators,
      summary
    });

  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
}
