export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  try {
    const { audioData, mimeType } = req.body;
    if (!audioData || !mimeType) return res.status(400).json({ error: 'Missing audioData or mimeType' });

    // Hive AI-generated audio detection
    const r = await fetch('https://api.thehive.ai/api/v3/hive/ai-generated-and-deepfake-content-detection', {
      method: 'POST',
      headers: { 'Authorization': 'Bearer ' + process.env.HIVE_API_KEY, 'Content-Type': 'application/json' },
      body: JSON.stringify({ input: [{ media_base64: 'data:' + mimeType + ';base64,' + audioData }] })
    });

    const d = await r.json();
    if (d.error || d.detail) return res.status(500).json({ error: d.error || d.detail });

    const classes = d.output?.[0]?.classes || [];
    const aiAudio = classes.find(c => c.class === 'ai_generated_audio');
    const realAudio = classes.find(c => c.class === 'not_ai_generated_audio');

    if (!aiAudio && !realAudio) {
      return res.status(500).json({ error: 'No audio classification found', debug: JSON.stringify(d).slice(0, 300) });
    }

    const aiScore = Math.round((aiAudio?.value || 0) * 100);
    const realScore = Math.round((realAudio?.value || 0) * 100);
    const isAI = aiScore > realScore;
    const verdict = isAI ? 'AI_GENERATED' : 'AUTHENTIC';
    const confidence = Math.max(aiScore, realScore);

    return res.status(200).json({
      verdict,
      confidence,
      ai_probability: isAI ? Math.min(95, Math.max(55, aiScore)) : Math.min(45, Math.max(5, aiScore)),
      authentic_probability: isAI ? Math.min(45, Math.max(5, realScore)) : Math.min(95, Math.max(55, realScore)),
      summary: isAI
        ? 'This audio was likely generated by an AI voice or music model.'
        : 'This audio appears to be authentic and not AI generated.'
    });

  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
}
